name: Render Keep Alive

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  ping-render:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Render Server
        run: |
          curl -f https://storage-system-kqwy.onrender.com/ping
